language: node_js
os:
- linux
dist: xenial
node_js:
- '10'
addons:
  apt:
    packages:
    - xvfb
    - libcairo2-dev
    - libpango1.0-dev
    - libjpeg-dev
    - libgif-dev
    - librsvg2-dev
  homebrew:
    update: true
    packages:
    - pkg-config
    - cairo
    - pango
    - libpng
    - jpeg
    - giflib
    - librsvg
env:
  global:
  - ELECTRON_CACHE: "$HOME/.cache/electron"
  - ELECTRON_BUILDER_CACHE: "$HOME/.cache/electron-builder"
cache:
  directories:
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
  - "$HOME/.npm/_prebuilds"
  - ".next/cache"
install:
- npm ci
deploy:
- tags: true
  provider: releases
  skip_cleanup: true
  file_glob: true
  file:
  - dist/*
  token: "$GH_TOKEN"
jobs:
  include:
  - if: branch =~ /v\d+\.\d+\.\d+/
    os: windows
    env:
    - PATH: "/c/Python27:/c/Python27/Scripts:$PATH"
    before_install:
    - choco install -y python2 gtk-runtime microsoft-build-tools libjpeg-turbo --allow-empty-checksums
    - curl -LO http://ftp.gnome.org/pub/GNOME/binaries/win64/gtk+/2.22/gtk+-bundle_2.22.1-20101229_win64.zip
    - 7z x gtk+-bundle_2.22.1-20101229_win64.zip -y -o/c/GTK
    script:
    - npm run dist:win
  - if: branch =~ /v\d+\.\d+\.\d+/
    os: osx
    osx_image: xcode11.3
    script:
    - npm run dist:mac
  - if: branch =~ /v\d+\.\d+\.\d+/
    os: linux
    script:
    - npm run dist:linux
  - if: branch = master
    os: linux
    before_install:
    - export DISPLAY=':99.0'
    - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    - npm install -g xvfb-maybe
    script:
    - npm run lint
    - npm run build
